package interfaz;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    logica.SistemaImpresion sistema = new logica.SistemaImpresion(100); 
    logica.ManejadorCSV manejador = new logica.ManejadorCSV();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarUsuarios = new javax.swing.JButton();
        CargarImpresiones = new javax.swing.JButton();
        NuevoUsuario = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPrioridad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Imprimir = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtEtiqueta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCola = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        CargarUsuarios.setText("Cargar Usuario");
        CargarUsuarios.addActionListener(this::CargarUsuariosActionPerformed);

        CargarImpresiones.setText("Cargar Impresiones");
        CargarImpresiones.addActionListener(this::CargarImpresionesActionPerformed);

        NuevoUsuario.setText("Registrar Usuario");
        NuevoUsuario.addActionListener(this::NuevoUsuarioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CargarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(CargarImpresiones, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(NuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuario)
                    .addComponent(txtPrioridad, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CargarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CargarImpresiones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrioridad, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Imprimir.setText("Imprimir siguiente");
        Imprimir.addActionListener(this::ImprimirActionPerformed);

        lblId.setBackground(new java.awt.Color(0, 0, 0));
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("usuario a eliminar:");

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::CancelarActionPerformed);

        txtEtiqueta.setColumns(10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        tablaCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Etiqueta", "Documento", "Tipo", "Usuario", "Prioridad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCola);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        try {
            // Ahora leemos el NOMBRE DEL USUARIO del cuadro de texto, ya no un ID numérico
            String nombreUsuario = txtEtiqueta.getText().trim();
        
            if (nombreUsuario.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa el Nombre del Usuario para cancelar su documento.");
                return;
            }

            // Llamamos a la lógica pasándole el String directamente ¡Adiós error rojo!
            sistema.eliminarDocumentoDeCola(nombreUsuario);
        
            // Refrescamos la tabla para que el cambio se vea en la pantalla gris
            actualizarTabla(); 
        
            // Limpiamos el campo y avisamos al usuario
            txtEtiqueta.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Si " + nombreUsuario + " tenía un documento, ha sido cancelado exitosamente.");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cancelar: " + e.getMessage());
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        modelo.Documento docImpreso = sistema.procesarImpresion();
    
        if (docImpreso != null) {
            JOptionPane.showMessageDialog(this, "Imprimiendo: " + docImpreso.getNombre());
            actualizarTabla(); // Para que desaparezca de la lista visual
        } else {
            JOptionPane.showMessageDialog(this, "No hay nada en la cola.");
        }
    }//GEN-LAST:event_ImprimirActionPerformed

    private void CargarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarUsuariosActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            String ruta = selector.getSelectedFile().getAbsolutePath();
    
            // Carga los usuarios a la Tabla Hash
            manejador.cargarUsuarios(ruta, sistema.getTablaUsuarios()); 
    
            // ACTUALIZA LA TABLA: Esto asegura que si hay documentos, se pinten de una vez
            actualizarTabla(); 
    
            JOptionPane.showMessageDialog(this, "¡Usuarios cargados con éxito!");
        }   
    }//GEN-LAST:event_CargarUsuariosActionPerformed

    private void CargarImpresionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarImpresionesActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);
    
        if (resultado == JFileChooser.APPROVE_OPTION) {
            String ruta = selector.getSelectedFile().getAbsolutePath();
        
            // Cargamos los documentos al montículo
            manejador.procesarArchivoImpresion(ruta, sistema); 
        
            // ESTO ES NUEVO: Para que los datos aparezcan en la pantalla gris
            actualizarTabla(); 
        
            JOptionPane.showMessageDialog(this, "Cola de impresión actualizada.");
        }
    }//GEN-LAST:event_CargarImpresionesActionPerformed

    private void NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoUsuarioActionPerformed
        // TODO add your handling code here:
        // 1. Capturamos los datos de la interfaz
        String nombre = txtNombreUsuario.getText().trim();
        String prioridad = txtPrioridad.getText().trim().toLowerCase();

        // 2. Validaciones básicas
        if (nombre.isEmpty() || prioridad.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        // 3. Verificamos que sea una prioridad válida según tu ManejadorCSV
        if (!prioridad.equals("prioridad_alta") && 
            !prioridad.equals("prioridad_media") && 
            !prioridad.equals("prioridad_baja")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Prioridad no válida. Usa: prioridad_alta, prioridad_media o prioridad_baja.");
            return;
        }

        // 4. Llamamos a tu lógica para registrar en la Tabla Hash
        try {
            sistema.registrarUsuario(nombre, prioridad); // Usa el método de tu clase SistemaImpresion
        
            // 5. Limpiamos los campos y avisamos
            txtNombreUsuario.setText("");
            txtPrioridad.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario '" + nombre + "' registrado con éxito.");
        
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
        }
    }//GEN-LAST:event_NuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton CargarImpresiones;
    private javax.swing.JButton CargarUsuarios;
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton NuevoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tablaCola;
    private javax.swing.JTextField txtEtiqueta;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPrioridad;
    // End of variables declaration//GEN-END:variables
    
    // ... aquí terminan los métodos de los botones ...

    public void actualizarTabla() {
        // 1. Conseguimos el modelo actual
        
        DefaultTableModel modelo = (DefaultTableModel) tablaCola.getModel();
    
        // 2. Limpiamos TODO lo que haya
        modelo.setRowCount(0); 

        // 3. Obtenemos el montículo
        var monticulo = sistema.getColaPrioridad();
    
        // 4. Llenamos con un ciclo
        for (int i = 1; i <= monticulo.getTamaño(); i++) {
            var registro = monticulo.getElementos()[i]; 
            if (registro != null) {
                modelo.addRow(new Object[]{
                    registro.getEtiquetaTiempo(),
                    registro.getDocumento().getNombre(),
                    registro.getDocumento().getTipo(),
                    registro.getDocumento().getNombreUsuario(), // Revisa que este método exista
                    "Prioridad " + registro.getValorPrioridad()
                });
            }
        }
    
        // 5. Esto obliga a la interfaz a refrescarse
        modelo.fireTableDataChanged();
        tablaCola.repaint();
}

}
